namespace _05.Comparendo.Presentacion.Consola.Models
{
    public class vwComparendo
    {
        public int Id { get; set; }
        public string? Numero { get; set; }
        public DateTime? Fecha { get; set; }
        public TimeSpan? Hora { get; set; }
        public int? DireccionId { get; set; }
        public int? LocalidadId { get; set; }
        public string? Placa { get; set; }
        public int? TransportePasajerosId { get; set; }
        public int? InfractorId { get; set; }
        public int? InfractorLicenciaConduccionId { get; set; }
        public int? InfractorDireccionId { get; set; }
        public int? InfractorEdad { get; set; }
        public int? TipoInfractorId { get; set; }
        public int? OrganismoLicenciaTransitoId { get; set; }
        public string? NumeroLicenciaTransito { get; set; }
        public int? PropietarioId { get; set; }
        public string? NombreEmpresa { get; set; }
        public string? Nit { get; set; }
        public string? TarjetaNumero { get; set; }
        public int? AgenteId { get; set; }
        public string? Patio { get; set; }
        public string? PatioDireccion { get; set; }
        public string? Grua { get; set; }
        public string? GruaPlaca { get; set; }
        public string? Consecutivo { get; set; }
        public string? Observaciones { get; set; }
        public int? TestigoId { get; set; }
        public int? DireccionTestigoId { get; set; }
        public int? EsatdoId { get; set; }
        public int? Naturaleza { get; set; }
        public string? SimitIdMovTrans { get; set; }
        public string? SkgIdMovTrans { get; set; }
        public string? MovTrans { get; set; }
        public string? CodiogoRUNTMovTrans { get; set; }
        public int? ModalidaTrasporteId { get; set; }
        public string? CodigoRUNTPasajeros { get; set; }
        public string? Pasajeros { get; set; }
        public int? SkgIdPasajeros { get; set; }
        public int? SimitIdPasajeros { get; set; }
        public string? CodigoRUNTRadioAccion { get; set; }
        public string? SkgRadioAccion { get; set; }
        public string? RadioAccion { get; set; }
        public string? SimitIdRadioAccion { get; set; }
        public int? RadioAccionId { get; set; }
        public int? CodigoInfraccionId { get; set; }
        public string? Infraccion { get; set; }
        public string? Descripcion { get; set; }
        public int? Salarios { get; set; }
        public int? DiasVencimiento { get; set; }
        public decimal? PorcentajeDescuento { get; set; }
        public decimal? PporcentajeRecargo { get; set; }
        public string? Inmovilizacion { get; set; }
        public int? EstadoInfraccion { get; set; }
        public int? TipoComparendos { get; set; }
        public int? MatriculadoId { get; set; }
        public string? DivipoMatricula { get; set; }
        public string? Ciudad { get; set; }
        public int? IdDepartamento { get; set; }
        public string? CodigoDIANCiudad { get; set; }
        public int? ClaseServicioId { get; set; }
        public string? CodigoRUNTServicio { get; set; }
        public string? Servicio { get; set; }
        public string? SkgIdServicio { get; set; }
        public string? SimitIdServicio { get; set; }
        public int? TipoVehiculoId { get; set; }
        public string? CodigoRUNTTipoVe { get; set; }
        public string? TipoVe { get; set; }
        public string? SkgIdTipoVe { get; set; }
        public string? SimitIdTipoVe { get; set; }
    }
}